### ISSUE TITLE
variable with lowercase trailing Ausgabe or Eingabe function name, used as void not as var

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#55] opened 2015-12-11 12:52 UTC
Prepare: Setup Parser Name for input to "Eingabe" and output to "Ausgabe"

zahleneingabe := 1 // problem string ".*eingabe$"
zahlenausgabe := 2 // problem string ".*ausgabe$"
Ausgabe zahleneingabe   // void,  not 1
Ausgabe zahlenausgabe  // void, not 2

**Comment by codemanyak** [comment] 2015-12-11 14:24
I just tested this algorithm with version 3.23-03 (though I did not write the line comments into the instructions, of course). Execution and code export, e.g. to C++ and Pascal, worked just fine. What exactly is the problem?
Here is the C++ export:
```
// program Issue55 
#include <iostream>

int main(void)
{
	// TODO Don't forget to declare your variables! 
	
	
	zahleneingabe = 1;
	zahlenausgabe = 2;
	std::cout << zahleneingabe << std::endl;
	std::cout << zahlenausgabe << std::endl;
	
	return 0;
}
```
What I can see is just that the variable highlighting doesn't work for these identifiers - I will see to fix that.
But please elucidate the exact malfunction.

**Comment by elemhsb** [comment] 2015-12-11 20:26
In the Executer.

**Comment by codemanyak** [comment] 2015-12-11 21:27
I can't reproduce the failure.

**Comment by codemanyak** [comment] 2015-12-11 21:54
The highlighting insufficiency is due to an inconsistent handling of keywords configured as parser preferences, input and output keywords in particular are case-independently replaced by the exact keyword even within variable names ("zahleneingabe" -> "zahlenEingabe"), which irritates the variable recognition.

**Comment by codemanyak** [comment] 2015-12-12 02:22
The highlighting part is fixed (will be available with 3.23-04), the executor problem is still not reproducible.

**Comment by elemhsb** [comment] 2015-12-12 07:32
![einausgabe](https://cloud.githubusercontent.com/assets/2959804/11760764/0631b59c-a0a8-11e5-8bce-0adbba816b9d.png)
I didn't recognize the warning, i put all into one "Anweisung", but see uppercase zahlen*E*ingabe and zahlen*A*usgabe ... Version was 3.23.03 to nightly version fesch/master 74f99eb35 problem still exists.
I will checkout codemanyak/master soon.

**Comment by codemanyak** [comment] 2015-12-12 14:21
These analyser warnings are irrelevant for the execution (to ged rid of the uppercase warnings just uncheck all Analyser preferences attributed with "(LUX/MEN)").
I executed it with separated instructions and as part of a single instruction element (according to your screenshot, but without the empty line!) without problems.
**Obviously the empty line is the problem!**
Drop it, and all will be fine. If you want to separate several instruction groups, just put them into different instruction elements.

BTW: You will be welcome testing the codemanyak/master. The last four patches (3.23-04) haven't been merged into the codemanyak/master Head version yet, but this is no general show-stopper.
I will be offline for three days now. Looking forward for your comments.

**Closed by codemanyak** 2015-12-12 14:21 UTC

**Comment by elemhsb** [comment] 2015-12-15 05:57
Yes, in this (constructed) example the empty line is the problem.  The occasion weithin the IF Statement could not reproduced. With actual software versions. :-)

BTW: it didn't build today ...

**Comment by elemhsb** [comment] 2015-12-15 19:52
BTW. I would test codemanyak-Structorizer.Desktop but i can't get it build.
$ ant
...
-do-compile:
    [javac] Compiling 68 source files to /tmp/github/codemanyak-structorizer/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /tmp/github/codemanyak-structorizer/src/lu/fisch/structorizer/elements/Root.java:2121: error: cannot find symbol
    [javac]     					Integer count = myInitVars.putIfAbsent(varName, 1 << threadNo);
    [javac]     					                          ^
    [javac]   symbol:   method putIfAbsent(String,int)
    [javac]   location: variable myInitVars of type Hashtable<String,Integer>
    [javac] /tmp/github/codemanyak-structorizer/src/lu/fisch/structorizer/elements/Root.java:2128: error: cannot find symbol
    [javac]     					Integer count = myUsedVars.putIfAbsent(varName, 1 << threadNo);
    [javac]     					                          ^
    [javac]   symbol:   method putIfAbsent(String,int)
    [javac]   location: variable myUsedVars of type Hashtable<String,Integer>
    [javac] /tmp/github/codemanyak-structorizer/src/lu/fisch/structorizer/executor/Executor.java:1607: error: cannot find symbol
    [javac] 							nLevels = Integer.parseUnsignedInt(tokens.get(1));
    [javac] 							                 ^
    [javac]   symbol:   method parseUnsignedInt(String)
    [javac]   location: class Integer
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 1 warning

BUILD FAILED
/tmp/github/codemanyak-structorizer/nbproject/build-impl.xml:908: The following error occurred while executing this line:
/tmp/github/codemanyak-structorizer/nbproject/build-impl.xml:257: Compile failed; see the compiler error output for details.

**Comment by fesch** [comment] 2015-12-15 20:03
@codemanyak : I suppose a wrongly committed file or package ...

**Comment by codemanyak** [comment] 2015-12-15 21:39
I'll have a look at it. Possibly a merging defect.

**Comment by codemanyak** [comment] 2015-12-16 00:00
Just tried to compile with the codemanyak/Structorizer.Desktop/master version - no problem.
I might send yout an executable Jar file if the problems with your configuration can't be fixed that easily.

**Comment by elemhsb** [comment] 2015-12-16 11:43
Now i get codemanyak/Structorizer.Desktop/master compiled and work, with newer *jdk1.8.0_66* from java.com and *ant* build from command line.
The Debian 8 distributed *older* openjdk-7-jdk:amd64 -- 7u91-2.6.3-1~deb8u1 failed on it.
Thanks to you for the hint "your configuration" :-) 

There are now 100 new [javadoc] warnings and errors with " < ", " <= ", ... which i could ignore ...
