### ISSUE TITLE
C import (grammar issue): parsing of C function pointers does not work

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#489] opened 2017-12-06 11:53 UTC
The following definition
```c
typedef union {
	void		*(*funcptr)();	/* Function returning "void *" */
	void		(*funcnull)();	/* Function returning nothing */
	cob_field	*(*funcfld)();	/* Function returning "cob_field *" */
	int		(*funcint)();	/* Function returning "int" */
	void		*funcvoid;	/* Redefine to "void *" */
							/* stdcall variants */
	void		*(__stdcall *funcptr_std)();
	void		(__stdcall *funcnull_std)();
	cob_field	*(__stdcall *funcfld_std)();
	int		(__stdcall *funcint_std)();
} cob_call_union;
```
leads to
```
error.syntax in file "C:\dev\test.c"

Preceding source context:
   43:   typedef union {
   44:       void        *» (*funcptr)();    /* Function returning "void *" */

Found token '('

Expected: ')' | '*' | ',' | Id
```

Note: I'm aware that this won't "work" with anything other than *maybe* C code export, but it would be nice to fix the grammar error (and/or to be able to skip these tokens #470).

**Comment by codemanyak** [comment] 2017-12-06 22:26
Won't find the time for it this year anymore. I label it as inconvenient.

**Comment by codemanyak** [comment] 2018-03-26 20:25
After having failed to tweak the underlying modified ANSI C grammar, I now managed successfully to adopt the grammar from Annex A of the ISO/IEC 9899:TC3 draft of ANSI C99 for GOLDParser.
This should let function types pass. But concepts, symbols and rules are totally different from the recently used grammar such that the diagram building in the CParser will have to be rewritten completely.
Because of still lacking time this will take me at least two months.

**Comment by GitMensch** [comment] 2018-03-27 06:52
This is still good news. Can you add the new Grammar here in the meanwhile (or likely better: a commit to vcs using a new grammar name).

**Comment by codemanyak** [comment] 2018-03-27 11:14
@GitMensch 
> Can you add the new Grammar here in the meanwhile (or likely better: a commit to vcs using a new grammar name)

Here you are: [codemanyak/Structorizer.Desktop/master](https://github.com/codemanyak/Structorizer.Desktop/commit/e37219517db6151e4695e59a28513e2ca3ee7e99)

**Comment by codemanyak** [comment] 2018-04-05 15:01
Well, I celebrated too early. My new C grammar drives the parser into an EmptyStackException... :disappointed:

**Comment by codemanyak** [comment] 2018-04-12 19:54
ANSI C 99 grammar corrected, plugin made visible in parsers.xml.
(Diagram generation still doesn't work, but the parser at least accepts the C files now.)
To be found on codemanyak/Structorizer.Desptop/master.

**Comment by codemanyak** [comment] 2018-06-24 20:39
@GitMensch 
An alpha version of the C99Parser that copes with the given example file and also most C files Structorizer had been able to import via the recent CParser can now be downloaded and built from codemanyak/Structorizer.Desptop/master. Alternatively, here is a prepared jar file that offers both C parsers.

**Comment by codemanyak** [comment] 2018-06-27 02:15
Updated test Jar file for C99 import:

[Structorizer_3.28-05alpha2.zip](https://github.com/fesch/Structorizer.Desktop/files/2139566/Structorizer_3.28-05alpha2.zip)

**Comment by GitMensch** [comment] 2018-06-27 16:24
Hi @codemanyak , I didn't tested C code import since a while and did this with some complex sources from GnuCOBOL source repository.

libcob/common.h (which was the source for the original sample) leads to:

ANSI C

~~~
Preceding source context:
  974:   
  975:   typedef long long » cob_flags_t;

Found token UserTypeId (cob_flags_t)

Expected: int | ')' | '*' | ',' | Id
~~~

ANSI C99:

~~~
Preceding source context:
 1108:   
 1109:   typedef struct __cob_fp_128 {
 1110:       unsigned long long    fpval[2];
 1111:   } cob_fp_128;
 1112:   
 1113:   /* Internal representation of decimal numbers */
 1114:   /* n = value / 10 ^ scale */
 1115:   /* Decimal structure */
 1116:   
 1117:   typedef struct __cob_decimal {
 1118:       » mpz_t        value;            /* GMP value definition */

Found token Identifier (mpz_t)

Expected: '_Bool' | '_Complex' | char | const | double | enum | float | int | long | restrict | short | signed | struct
        | union | unsigned | UserTypeId | void | volatile | wchar_t
~~~

libcob/common.c leads to "**FILE PREPARATION ERROR**" with both parsers (what does this mean exactly?)

Simpler sources like the one from https://svn.code.sf.net/p/open-cobol/contrib/trunk/tools/ocsort seem to work, headers that are written to work both with C and C++ fail, I guess it should be possible to adjust the internal preparser to remove the offending part or even handle `__cplusplus` defines:

~~~
Preceding source context:
   82:   // function header for external call
   83:   //
   84:   // preparser instruction (not parsed!): #ifdef __cplusplus
   85:   extern » "C" {

Found token StringLiteral ("C")

Expected: '(' | ')' | '*' | ',' | ';' | '[' | '_Bool' | '_Complex' | auto | char | const | double | enum | extern
        | float | Identifier | inline | int | long | register | restrict | short | signed | static | struct
        | typedef | union | unsigned | UserTypeId | void | volatile | wchar_t
~~~

Testing some win32 files fail with the more or less standard defines: BOOL APIENTRY HANDLE DWORD LPVOID, ... Do you think it is reasonable to add these to the grammar or possibly pre-define them in a list the user may extend/change?

**Comment by codemanyak** [comment] 2018-06-28 01:50
@GitMensch 
Some answers:
- `long long` isn't supported by the old C grammar, neither is an `unsigned` without following `int` or the like.
- You get past the `mpz_t` error be appending this (obviously undefined) type name to the import  configuration ("Externally defined type names").

> Testing some win32 files fail with the more or less standard defines: BOOL APIENTRY HANDLE DWORD LPVOID, ... Do you think it is reasonable to add these to the grammar or possibly pre-define them in a list the user may extend/change?

Possibly you may put the defines either to the externally defined typenames or to the redundant preprocessor names:
![grafik](https://user-images.githubusercontent.com/15326471/42008272-e6ff8546-7a84-11e8-834e-f03f17da815f.png)

W.r.t. `typedef	char * cobchar_t;` I have no idea. I can reproduce it loading "common.h", though I dont find it mentioned in your comment any longer. You seem to have dropped it.

**Comment by codemanyak** [comment] 2018-06-28 01:57
This new jar file contains enhancement #552, which makes testing a lot easier. There are no new C99Parser changes.

[Structorizer_3.28-05alpha3.zip](https://github.com/fesch/Structorizer.Desktop/files/2143444/Structorizer_3.28-05alpha3.zip)

**Comment by GitMensch** [comment] 2018-07-04 08:33
How are "externally defined type names" imported?

I suggest to add a third option to both C imports, allowing a redefinition for the preparser phase (something like `BOOL=boolean, TRUE=true, FALSE=false, DWORD=unsigned long`) and pre-fill it according to https://docs.microsoft.com/en-us/windows/desktop/WinProg/windows-data-types and standard type definitions, found at https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/sys/types.h / https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/crtdefs.h

I think it is more reasonable to do this once instead of parsing the header files with any import...

**Comment by codemanyak** [comment] 2018-07-04 10:04
@GitMensch 
> I suggest to add a third option to both C imports, allowing a redefinition for the preparser phase (something like BOOL=boolean, TRUE=true, FALSE=false, DWORD=unsigned long)

This mixes constants with type names. For the parser, it's sufficient to know that certain name designates some type not defined in the grammar. It's not necessary to know what they mean in particular. Unknown constant names aren't show stoppers. (They can still be defined in the Structorizer diagrams - if we get there at least.)
The WinAPI and MinGW types you named exemplarily aren't standard C types, although they might often be used. Other libraries could define the same words in a different way.
So your proposal won't bring a substantial improvement, I'm afraid. I will ponder it, nevertheless.

Meanwhile I managed to clarify what caused the strange (and context-dependent!) errors like the one I bumped into with "common.h" after having sorted out all type name and redundant symbol issues via tuning the respective options. They may read like
```
Preceding source context:
 2142:   extern cob_field *cob_intr_standard_compare        (const int, ...);
 2143:   extern cob_field *cob_intr_test_formatted_datetime    (cob_field *, cob_field *);
 2144:   
 2145:   extern cob_field *cob_intr_integer_of_formatted_date    (cob_field *,
 2146:                                    cob_field *);
 2147:   
 2148:   /*******************************/
 2149:   
 2150:   /*******************************/
 2151:   /* defines for MicroFocus C -> COBOL API */
 2152:   typedef    char *        Â» cobchar_t;

Found token UserTypeId (cobchar_t)

Expected: '*' | const | restrict | volatile | '(' | ')' | ',' | '[' | Identifier 
```
If I remove some redundant lines before this passage then the error doesn't occur.

The reason is that the StreamTokenizer class I used for the typedef preparations provides wrong line counts. This way, the replacements are done in wron block ranges. As it seems, the counting failures happen in larger comment blocks. Now the good question is how to mend it...

**Comment by GitMensch** [comment] 2018-07-04 12:14
I agree, as long as the parser passes type names 1:1 to the grammar and doesn't stumble over TYPE* it is fine to leave them in. But I still suggest to pre-fill the "external defined type names" with the definitions mentioned in the three linked places as it would more often help than hinder.

As I'm not sure about the status of the internal C pre-parser (it is the same for both grammars, isn't it?):
*if* a parsed header would do `#define TYPE value` then `TYPE` would be replaced anywhere in the code (possible with nothing, if `value` is nothing), the "external defined" and "redundant" lists wouldn't apply, correct?

**Comment by codemanyak** [comment] 2018-07-04 21:01
@GitMensch 
> I agree, as long as the parser passes type names 1:1 to the grammar and doesn't stumble over TYPE* it is fine to leave them in.

Yes, configured type names would pass as are (1:1). As Structorizer ignores most declarations anyway, it doesn't matter much. Pointer type specifications "TYPE*" are also imported as are, though this wil cause syntax errors on an execution attempt. Doesn't matter either, while pointers aren't supported.
On export, a type name "BOOL" would even be interpreted as intended. Value defines like "TRUE" would be reported as undeclared variables but are at least readable in the diagram. The user might replace them with "true", if execution is intended, or maybe introduce a constant definition `const TRUE <- true` in some includable diagram.

> But I still suggest to pre-fill the "external defined type names" with the definitions mentioned in the three linked places as it would more often help than hinder.

Maybe we could add some checkboxes, which introduce one of these specific API definitions (WinAPI, MingW etc.) as a whole each.

> As I'm not sure about the status of the internal C pre-parser (it is the same for both grammars, isn't it?) ...

Yes, it is.

> ... if a parsed header would do #define TYPE value then TYPE would be replaced anywhere in the code (possible with nothing, if value is nothing), the "external defined" and "redundant" lists wouldn't apply, correct?

It is correct, because the hash map `defines` is first filled with the configured redundant keys, then the preprocessor defines in the code will be analysed and may override the empty defines of the preferences.

**Comment by codemanyak** [comment] 2018-07-04 21:17
Fortunately I found a heuristic workaround for the lagging line counts of the StreamTokenizer. Now the files pass. There is still an issue with "duplicate" struct type definitions, i.e. definitions of the kind
```c
typedef structname struct{ ... } typeid;
```
Structorizer import (C99 in particular) still fails to produce several linked (synonym) type definitions for the common struct. And it may not be quite easy because the struct initializers will have to be labelled with exactly one of the type names. So the matching requires some efforts. Should be feasible to solve, though.
Another flaw is that the storage class "external" fools the diagram builder.

**Comment by codemanyak** [comment] 2018-07-27 14:37
Function pointers do not spoil C code import with C99Parser.
The type name aliases for named structs as mentiond in https://github.com/fesch/Structorizer.Desktop/issues/489#issuecomment-402560547 work now, too, in C99Parser.

So I close this issue for now.

**Closed by codemanyak** 2018-07-27 14:37 UTC
Labels: inconvenient
