### ISSUE TITLE
Bug: The following nsd-file could not loaded

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#282] opened 2016-11-07 18:08 UTC
Hi Kay,

the newest version will not read (open) the following nsd file:
`<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:nsd="http://structorizer.fisch.lu/" version="3.25-05" preRepeat="solange" preFor="von" preLeave="leave" postForIn=" aus" stepFor=", mit = " ignoreCase="false" preCase="falls" preForIn="in" input="lies" preReturn="return" preExit="exit" preAlt="wenn" preWhile="solange" output="schreibe" postFor="bis" text="&#34;arraytest&#34;" comment="&#34;&#34;" color="ffffff" type="program" style="nice">
        <children>
                <instruction text="&#34;a &#60;- {1,3,5,7}&#34;" comment="&#34;Array-Initialisierung&#34;" color="ffffff" rotated="0" disabled="0"></instruction>
                <instruction text="&#34;i &#60;- 0&#34;" comment="&#34;&#34;" color="ffffff" rotated="0" disabled="0"></instruction>
                <for text="&#34;in i aus {a}&#34;" comment="&#34;&#34;" counterVar="i" startValue="" stepConst="" style="TRAVERSAL" insep=" aus" color="ffffff" disabled="0">
                        <qFor>
                                <instruction text="&#34;schreibe i&#34;" comment="&#34;&#34;" color="ffffff" rotated="0" disabled="0"></instruction>
                        </qFor>
                </for>
        </children>
</root>`

The diagram (exportet from the previous version) looks like
![arraytest](https://cloud.githubusercontent.com/assets/18035140/20069523/4706f5a8-a51d-11e6-83df-f2e9e4882165.png)
The error-output (from Open Recent File) is:
`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.util.HashMap.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.parsers.D7Parser.setKeyword(D7Parser.java:1144)
        at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:401)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:686)
        at lu.fisch.structorizer.gui.Diagram.openNSD(Diagram.java:1176)
        at lu.fisch.structorizer.gui.Menu$83.actionPerformed(Menu.java:1195)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(BasicMenuItemUI.java:943)
        at javax.swing.JMenuItem.fireMenuDragMouseReleased(JMenuItem.java:585)
        at javax.swing.JMenuItem.processMenuDragMouseEvent(JMenuItem.java:482)
        at javax.swing.JMenuItem.processMouseEvent(JMenuItem.java:428)
        at javax.swing.MenuSelectionManager.processMouseEvent(MenuSelectionManager.java:328)
        at javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(BasicPopupMenuUI.java:859)
        at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2448)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2340)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2339)
        at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2339)
        at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2298)
        at java.awt.Component.dispatchEventImpl(Component.java:4768)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

Also the batch call ( _Structorizer/structorizer.sh -x bash arraytest.nsd_) throws the follwing exception
`Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.parsers.D7Parser.setKeyword(D7Parser.java:1144)
        at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:401)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:686)
        at Structorizer.export(Structorizer.java:244)
        at Structorizer.main(Structorizer.java:124)Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.parsers.D7Parser.setKeyword(D7Parser.java:1144)
        at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:401)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:686)
        at Structorizer.export(Structorizer.java:244)
        at Structorizer.main(Structorizer.java:124)`

Hope that helps.
Fine regards
Rolf

**Comment by codemanyak** [comment] 2016-11-08 08:44
Caused by the very same line of code as #281. Will be fixed together.

**Closed** 2016-11-08 09:25 UTC
Labels: bug, duplicate
