### ISSUE TITLE
Problems with editing a program text

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#395] opened 2017-04-18 10:52 UTC
Hi,

I found out, that I sometimes cannot edit a text field (in the dialog), if the text was selected. Only one character was accepted.

To test:
Start structorizer new - not only a new document.
Double click to change the program name.
Select the three question marks with the mouse
Start writing a new name.

Fine regards
Rolf

**Comment by codemanyak** [comment] 2017-04-18 17:06
I tried with Structorizer 3.26-05 under Windows Vista, Windows 7, SUSELinux, and Debian 8, but could not reproduce the problem under any of these OS environments. I can write text without limitations, no matter whether the question marks had been selected or not.
What enviroment are you working in? I guess with some Debian version? Possibly a very lean one?

**Comment by reks99** [comment] 2017-04-18 17:48
It is Structorizer 3.26-05 as well. The environment is Debian 8 with trinity 4.04 as desktop environment.

I will try other versions to find out since when the problem starts.
Fine regards
Rolf

**Comment by reks99** [comment] 2017-04-21 14:01
Hi,
as promised, I tested an older version - oldest was 3.24-11. The problem sems not to be there.

When think about the behavior I find out:
1. the text is selected for overwrite
2. when overwrite the text is deleted by the first new character
3. the new character is (still) selected for overwrite and the next new character overwrites the previous character and so on.

Hope it helps you to find something it causes the problem
Fine regards
Rolf

**Comment by codemanyak** [comment] 2017-04-21 15:27
Somewhat spooky, isn't it? The editor uses a standard JTextArea. The only changes recently made were to establish the tab keys as focus traversal keys (issue #163) a year ago and a switch-command-mode-dependent focus control (issue #180) in July 2016. I can't see that these were to be blamed.
Again, I still can't reproduce the effect (or defect) under any OS or Structorizer version.
Therefore, some more questions:

- What Look & Feel are you using? Does the Look & Feel matter or can you reproduce the mis-behaviour under any of them?
- In theory, the behaviour should occur in any JTextArea (e.g. the comment field, too) with arbitrary previous content (i.e. not only with "???").
- Have you tried on a different machine or with a different OS version?

**Comment by reks99** [comment] 2017-04-23 09:22
Hi,

- I use the same Look&Feel since years (around 10 Years) and have only a few virtual machines with gnome

- The "miss"-behavior occurse in other comment fields as well. The description was a simple method to reproduce the behavior here more often, because.the "error" does not come up every time.

- At all machines (two Laptops and a desktop machine) the behavior is identical. I can try a Live-System, like Knoppix for another test.
Fine regards
Rolf

**Comment by codemanyak** [comment] 2017-04-23 12:52
@reks99 Thank your for your additional information. It's very intersting to know that the phenomenon appears only occationally. This is where my next questions are related to:

- Is it bound to an entire Structorizer session? That is, does the session either start with misbehaviour and does it then persist, or if a session starts with normal behaviour will you then be safe of it? Or may it randomly occur within one and the same session?
- You wrote you may circumvent the inconvenience by first erasing the selection content. Does the phenomenon return if you select a text span therafter?
- May there be a corellation with a number of silent NullPointerExceptions (look in the terminal window if you start Structorizer via `structorizer.sh &`) on session start? (These are results to a race condition that has not been identified exactly.)

You wrote two days ago:

> It is Structorizer 3.26-05 as well. The environment is Debian 8 with trinity 4.04 as desktop environment.

I guess you meant trinity (TDE) **1**4.0.4? You wrote today that you also use Gnome on some virtual machines. If I interpret you right then TDE or Gnome make no difference for the issue?

**Comment by GitMensch** [comment] 2017-04-24 08:35
Just a wild guess: is it possible that the "updated" system cater for insert mode (different than it did before)? @reks99 Is the behavior identical no matter if you press the insert key (=toggle insert mode)?

**Comment by reks99** [comment] 2017-04-25 08:13
Hi,

> Is the behavior identical no matter if you press the insert key (=toggle insert mode)?
Yes, there is no difference with or without togglec insert key.
HTH
Rolf

**Comment by reks99** [comment] 2017-04-25 08:42
Hi

> Is it bound to an entire Structorizer session? That is, does the session either start with misbehaviour and does it then persist, or if a session starts with normal behaviour will you then be safe of it? Or may it randomly occur within one and the same session?

It is very difficult to report.
I just had a session, where the phenoma was constant by editing every (3) nsd elements but in the next session it occures only when change the name of the program.

In another test I found the following:
1. When selecting the text to edit with the key combination shift POS1 the dialog behaives normal.
2. When selecting the text with the mouse from right to left the problem is shown.
3. When selecting not all characters, no problem.

In the current session the problem comes up randomly ;-) i.e. some times now problem, some times only at every second cycle.

Very difficult to find a reproducable scenario.

Fine regards
Rolf

**Comment by codemanyak** [comment] 2017-04-25 11:30
This rather erratic "symptomatology" suggests me that it is hardly due to a programming bug in Structorizer. I guess it is rather some emergent effect induced by ba a complex interference of several concurrent components, among which might be:

- A time-critical dependency chain in Structorizer
- the specific grid bag layout of the Structorizer element editor
- Java Swing (not thread-save)
- Java RE
- the operating system
- the desktop (including some settings)
- the virtual machine hypervisor
- the computer(s)

What seems to outrule the first of the listed potential contributors is that during element editing most of the rather time-consuming application-specific diagram, menu, and toolbar redrawing mechanisms are practically inactive.
Perhaps you might help clarifying what's going on by trying another (very simple) Java-based structogram editor, the [jar file](http://ssl.whiledo.de/sonstiges/download/struktogrammeditor1.7.2.jar) of which is easily downloadable (though not open-source, unfortunately - so I don't know whether it also uses Swing JTextAreas): The "Struktogrammeditor" from the [whiledo.de](http://www.whiledo.de/index.php?p=struktogrammeditor) homepage.
Just double-click the downloaded jar file or write `java -jar struktogrammeditor1.7.2.jar`. If you can observe simalar effects on editing the elements dragged into the diagram then it would be clear that it has nothing to do with Structorizer. Unfortunately, it would not tell us anything if you can't provoke the defective behaviour on that other editor.

**Comment by reks99** [comment] 2017-04-25 12:50
Hi
I tested the struktogrammeditor1.7.2.jar and it behaves the same way i.e. more or less randomly the chars are selected after an overwrite.

Fine regards
Rolf

**Comment by codemanyak** [comment] 2017-04-25 13:29
Thanks a lot, Rolf.

> I tested the struktogrammeditor1.7.2.jar and it behaves the same way i.e. more or less randomly the chars are selected after an overwrite.

Hence, it's no Structorizer-specific issue but a problem among OS and Java, obviously. The only fact that did not fit into this conclusion would have been that your test with Structorizer 3.24-11 didn't show the misbehaviour, but...

> BTW: Except the test of structorizer 3.24-11 all test didn't run in virtual machines (because the vm's use different drivers for the virtual graphic device).

This is the eventual proof that it's not our fault. Consequently, running an up-to-date Structorizer version in a Virtual machine should not show the defect, either. As you said, the drivers of the "real" OS or the OpenJava package (I assume you aren't using the Oracle Java?) are to be blamed.

I dare to close this issue, therefore.

**Closed by codemanyak** 2017-04-25 13:29 UTC
