### ISSUE TITLE
Parser Exceptions do not contain any source reference

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#627] opened 2018-10-24 09:13 UTC
Found out when checking #626 which raised

~~~
**Severe error on importing file "C:\temp\test.cbl":
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
~~~

The message is prepared in CodeParser.java around line 632:

```java
			catch (Exception e2) {
				error = "**Severe error on importing file \"" + _textToParse + "\":\n" + e2.toString();
				// START KGU#484 2018-04-05: Issue #463
				//e2.printStackTrace();
				getLogger().log(Level.WARNING, error, e2);
				// END KGU#484 2018-04-05
			}
```

but `e2` doesn't contain any entry in its stacktrace.

The error was raised in `java.lang.String.substring(int, int)` called by COBOLParser.java (getContentToken_R) around line 8412, having this information in the message/stracktrace would have been helpful.

**Comment by codemanyak** [comment] 2018-10-24 14:22
Interesting. I will try to reproduce this...

**Comment by GitMensch** [comment] 2018-10-24 16:17
I was able to reproduce it with the following variable declaration

```cobol
       78 stuff value
                                            '  +                        
      -    ''.
```

and current release zip from GitHub Releases.

**Comment by codemanyak** [comment] 2018-10-24 22:04
Okay, I can reproduce a StringIndexOutOfBoundsException (which is bad enough), but what I can't reproduce is an empty exception. You must of course be aware that the stacktrace is written to the structorizer0.log fle in `~/.structorizer`. Unfortunately I haven't found a way to force a flushing of logging records to the log stream. So you will usually have to leave Structorizer in order to see the log file content. With my tests, the respective log record looked like this:
[log_extract.txt](https://github.com/fesch/Structorizer.Desktop/files/2512460/log_extract.txt)
Of course we could print the stacktrace to any other file or device

**Comment by GitMensch** [comment] 2018-10-25 05:41
Hm, the stacktrace in your log is fine and it is also in mine.

It was shown as "empty" `[]` for `e2` during debugging (normally I get something in there)?!?

I think it is reasonable to normally don't show it to the user in the message but can I suggest to add it in "OK & copy to clipboard" as "Details"?

**Comment by codemanyak** [comment] 2018-10-25 09:06
> can I suggest to add it in "OK & copy to clipboard" as "Details"?

Oh, you suggest it alright ;-). I will have a look at it. But then the good question arises, which other exceptions to include as well...

**Comment by GitMensch** [comment] 2018-10-25 09:37
> But then the good question arises, which other exceptions to include as well...

I'd put any exception in the clipboard text...

**Comment by codemanyak** [comment] 2018-10-29 05:50
> I think it is reasonable to normally don't show it to the user in the message but can I suggest to add it in "OK & copy to clipboard" as "Details"?

I did so now, nearly at least: The stacktrace is just appended to the error message for te clipboard, provided it was a caught exception that led to the error message. Already committed to bugfix branch.

**Closed** 2018-11-22 10:15 UTC
Labels: enhancement
