### ISSUE TITLE
Executor: use equals method when comparing strings

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#406] opened 2017-05-16 10:29 UTC
![grafik](https://cloud.githubusercontent.com/assets/6699539/26101798/b7da58e2-3a32-11e7-8a31-6d0bdac10323.png)

As the Executor knows what type file_status is it may be able to use the equals method even when a NSD uses an equals sign which is more language-agnostic than writing `file_status.equals("00")`.

**Comment by codemanyak** [comment] 2017-05-16 11:04
The problem is not the translation of the equality operator but the defective expression on the right-hand side: `"00" or "10"` is not a valid expression in Structorizer and most HLLs.
I have already invested some efforts to mend many of the "defective" COBOL conditions on import. This works more or less fine if there is at least an orphaned comparison operator like in `test > 3 and < 15`. Unfortunately I haven't had a good idea how to do anything meaningful with expressions like the one above where the only chance is to test upon guessed types. But even then it isn't trivial in the given parsing context to produce the correct expression: `file_status = "00" or file_status = "10"`. The damned COBOL syntax defines conditions simply as lists of tokens, there is no operator hierarchy in the grammar (other than for arithmetic expressions)!

**Comment by codemanyak** [comment] 2017-05-16 11:10
BTW: The Executor replaces the equality sign quite fine if it gets syntactically valid expressions that convey enough type information. I won't do anything to enable Executor to evaluate defective expressions.
So I would like to close this issue and rather concentrate on #407.

**Closed** 2017-05-16 11:37 UTC

**Comment by GitMensch** [comment] 2017-05-16 12:07
Note concerning the COBOL tokens in expressions: It may help to have a look at the way GnuCOBOL handles nearly the same grammar tokens:

The main entry point for this is in [cobc/typeck.c][1],  `cb_build_expr()` which gets a list of token trees that are simply iterated. The main part it is doing is handling the class checks first (and generates function calls for these), leaving most of the other parts to `cb_expr_shift()`.

Just import it from C to NSD, then clean it, then export to Java ;-)
... it likely works better to do the first part manually or even doing the complete process with the brain tool.

[1]:https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnu-cobol-2.0/cobc/typeck.c

**Comment by codemanyak** [comment] 2017-05-16 12:15
Thank you for the source file link. Seems to be enough material for the brain tool...

**Comment by GitMensch** [comment] 2017-05-17 10:55
@codemanyak I'm happy when you are happy with the current status. The COBOL import is definitely more work then other languages that are nearer to Java like C. I think the Java import, if a good grammar exists - which wasn't the case for COBOL, would be similar to the C import.
And I assure you, a COBOL *compiler* is much more work (you need to check for all kinds of stuff that we can simply ignore in Structorizer) and the code generation is much more complex than the generation of the NSD :-) [not to speak of the runtime library you need, too]

Thank you for your work on the COBOL import! (The export, if you really want to do it would be much easier as you can generate structured programs with "simple" data types like `USAGE UNSIGNED-BINARY` - but I think the more complicated import is the more important one.)

**Comment by codemanyak** [comment] 2017-05-18 01:05
@GitMensch 
> I assure you, a COBOL compiler is much more work.

Oh that is for sure. I have no doubt about that, of course I know that. I just uttered some slight frustration. Don't take it for serious. COBOL has not actually become an intriguing language for me. It's structure is rather repelling, seems inconsistent and redundant (many strange and overlapping constructs, certainly for historical reasons). Nevertheless it's an interesting work but it's a lot of work, way more than I had planned to commit for.
I still don't see an end. Many really important aspects haven't solved yet (e.g. tables, records, internal calls (PERFORM section etc.). And the more of it is done the more seems to be lacking. Well, I don't complain. Without it, the C Parser wouldn't exist either.
