### ISSUE TITLE
Structorizer does not save my file

### ISSUE THREAD

**Issue by scorneil** [fesch/Structorizer.Desktop#339] opened 2017-02-01 14:35 UTC
I started having this issue yesterday. Today, one of my students is having the same problem ...

I'm using Windows 10 + Structorizer 3.26.02 + JRE jre1.8.0_121 64-bit
student is using same but with JRE 32-bit

When I start from Structorizer.bat in command line, it seems that the program is looking for a language file that it cannot find (attachment). There are no errors.
![commandline](https://cloud.githubusercontent.com/assets/25483575/22510901/0dd82292-e894-11e6-8ed7-ad5177612775.PNG)

**Comment by fesch** [comment] 2017-02-01 15:02
Vrersion 3.26.02 has been uploaded only a few hours ago, so yesterday you had still 3.26.01 ;-)

The text "Loading now ... " is an information, not a warning nor an error messages. It tells you that the corresponding file has been loaded, not that it cannot find it ...

**Comment by codemanyak** [comment] 2017-02-02 00:06
@scorneil I would like to draw your attention to the questions Bob added to his comment after having sent it as mail.
Well, if I understand you well (or if I guess well), you want to say that you can edit a diagram, possibly even execute it, but Structorizer ignores your saving attempt without raising an error message or writing some elucidating hint to the console? Does it just refuse to save but you can go on editing - or does the Structorizer window freeze? You just don't find the nsd file in the selected target cirectory though saving seems to have happened? Or don't you even see the file chooser menu?
It would be nice if you could describe what you did and what happened or didn't happen in more detail.
According to your report it didn't make a difference whether you tried with version 3.26-01 or 3.26-02. Is that right?

**Comment by codemanyak** [comment] 2017-02-02 00:23
@scorneil A well, just a wild guess that came to my mind: You have of course given your diagram a name different than "???", haven't you? Because while the proposed file name, which is derived from the diagram name, contains question marks you won't have a chance to get it saved on the file system.

**Comment by scorneil** [comment] 2017-02-02 07:05
Ha, ha ! You're absolutely right ! I just thought I'd be brief  :-)

I had 3.25 or 3.26, 2 days ago, when I first encountered the problem.
Yesterday; I noticed that there was a newer version. but I had the same
problem.
The student only worked with the latest version.

It's a really strange thing ... We both were able to use Structorizer for a
while without any problems. Then, later on, when we try to save our
nsd-file (not something hugely complicated or so), Structorizer seems to
save the file just fine ... It just doesn't show up on my pc.

If I then open some random other nsd-file, and then try to open the first
file again ... it shows up in the 'open file' menu (attachment 1). But if I
close Structorizer first, and then try to find that same file again ...
it's no longer there (att.2).







2017-02-01 16:02 GMT+01:00 Bob Fisch <notifications@github.com>:

**Comment by codemanyak** [comment] 2017-02-02 07:06
@scorneil Another investigation direction: You might check in the Java Control Panel, whether perhaps older Java versions are still active. If so deactivate them. Another try (though less likely to help here) might be to clear the Java Cache (also to be done via the Java Control Panel). You might want to have a look to the log sub-directory of the specified Java temp directory first...

**Comment by scorneil** [comment] 2017-02-02 07:26
@codemanyak : the log dir is empty (AppData/LocalLow/Sun/Java/Deployment/log). The Java Cache Viewer is showing me this :
* Applications : Structorizer
* Resources : Structorizer.jar, structorizer.png, version.txt, index.jnlp (all 01/02/2017)

I have only jdk1.8.0_112 and jre1.8.0_121. The Java Control Panel shows me the jre is used.

@codemanyak, @fesch : thank you both for your help !

**Comment by codemanyak** [comment] 2017-02-02 11:09
@scorneil 
Thank you for detailing the problem. I still haven't got exactly how it happens, though. Unfortunately, the two referenced attachments haven't been transported:

> If I then open some random other nsd-file, and then try to open the first file again ... it shows up in the 'open file' menu (attachment 1). But if I close Structorizer first, and then try to find that same file again ... it's no longer there (att.2).

Would you mind opening the GitHub issue in the browser and upload the screenshot files explicitly into your cited comment (press the pencil button "Edit comment") or into a new comment? Thanks for your cooperation.

**Comment by scorneil** [comment] 2017-02-02 11:27
@codemanyak Sure !
![1](https://cloud.githubusercontent.com/assets/25483575/22547570/8b422e0e-e942-11e6-8560-d1b0dd5d4529.PNG)
![2](https://cloud.githubusercontent.com/assets/25483575/22547571/8b428c00-e942-11e6-87ae-c40653a2bafe.PNG)

There's probably not all that much information in them anyway. The first img is a screenshot of the 'File Open' menu in Structorizer. The newly created and 'saved' file is visible : 'Test2.nsd'
The second img is the same thing, but after closing and restarting Structorizer : the file is gone.
It is also nowhere to be found on my computer.

**Comment by codemanyak** [comment] 2017-02-02 11:38
Puh, how strange is that! At the moment I try to explain it with a pending close or or renaming operation. But I don't see in the code what might cause it.
Yo wrote that you have to open an arbitrary NSD file first inbetwwen in order to see the previously created nsd file on next opening attempt. Does this mean that an open attempt immmediately after having saved the file (i.e. without having loading another file or closing Structorizer) does not show it in the file chooser?
Would you find a temporary file Structorizer<crude_characters>.nsd in your temp directory with the timestamp of your saving approach and containing the vanished content?

**Comment by scorneil** [comment] 2017-02-02 11:50
'Strange' it certainly is !   :-)

No, no, I didn't explain it very well. Sorry ! I don't HAVE to open another file.
When I save my .nsd, Structorizer thinks it is saving it just fine. I get no errors or warnings. 
If I leave Structorizer, with the nsd (which Structorizer thinks it has saved to my pc) still open, and I open up Windows explorer to go look for the nsd on my computer, the file just isn't there.
I opened the other random nsd-file to check if I could still find my original nsd back through Structorizer (file > open). And yes ! As long as I don't close Structorizer, Structorizer thinks it has saved my nsd file (but it hasn't).

Ouch. I hope you understand ...

**Comment by scorneil** [comment] 2017-02-02 11:55
Which temp folder is it you want me to look in ? 
I checked Window/temp and the Java/Deployment/tmp, but they're both empty.

**Comment by fesch** [comment] 2017-02-02 12:08
Is your Desktop really on the local PC or somewhere synched to an remote file-server?

**Comment by scorneil** [comment] 2017-02-02 12:08
@fesch  : Local pc

**Comment by fesch** [comment] 2017-02-02 12:11
OK. I just wanted to exclude any sych-problems, because I know that such may exist too.

**Comment by scorneil** [comment] 2017-02-02 12:11
Sure.

**Comment by codemanyak** [comment] 2017-02-02 12:46
@scorneil 

> Which temp folder is it you want me to look in ?

Well, I'm referring to the user-specific temporary files directory, Under Windows 7 it is `AppData/Local/Temp`.

> As long as I don't close Structorizer, Structorizer thinks it has saved my nsd file (but it hasn't).

But if you can see the file in the open file dialog (as you wrote above, cf attachment 1) then it must have been saved because the directory content is retrieved from the OS, not reproduced from a Structorizer-internal cache. And the mechanism works absolutely fine and reliably under Windows 7, Linux etc.
So the only reason I can think of is that either Java lies to Structorizer or the Windows 10 NTFS lies to Java. Maybe some buffering or journaling issue?
Just to make sure I have the correct impression of the behaviour:
When you just saved the file and stay in Structorizer, do you see the produced file in the file open dialog? If so and you check via explorer at the same time, does the file show up as well? Or not? If so, can you rename the file with explorer?
And does the "Recent file" list in the File menu show the filename already?

**Comment by scorneil** [comment] 2017-02-02 12:58
@codemanyak 
Windows 10 has a Temp folder in the same location. But nothing comes in from Structorizer ...

> 'Maybe some buffering or journaling issue?'
I'm completely out of my depth, but I was also thinking in the lines of 'buffer'.

> 'to make sure I have the correct impression of the behaviour:'
When I save the file and stay in S, I see the file in the file open dialog.  I can also see it in the 'recent files' dialog. I cannot see it in the Windows Explorer.
If I close S., and start it up again, then the file is gone from 'file open' and 'recent files'.

**Comment by codemanyak** [comment] 2017-02-02 13:30
This tells me that the JVM seems to virtualize the file system environment under Windows 10 in a radically new way. (I use the JavaRE version 1.8.0_121 or 1.8.0_111 under Windows 7 and there is no problem.)
This would be sound with the observation that the file is only visible in the Java VM world and is not committed to the real filesystem. As soon as you close Structorizer, the JVM is killed, to, and with it all the "virtual files". If I'm true then it would be the same with the preference settings - if you change some default then it would be gone on next Structorizer start (this should also include the recent file list, the current directory etc.) It should even apply to files created by the new Structorizer File API, i.e. using fileCreate(), fileWrite(), and fileClose() within a Structogram.
All these files should be visible in the Structorizer file open dialog (with filter set to "all files") but not in explorer if my suspicion were justified.
This would be a **fat** Java error! I haven't found anything about such a behaviour in current developer threads, though. Maybe there is a new configuration in the Java Control Panel...?

**Comment by fesch** [comment] 2017-02-02 13:35
Just tried on my brand new Windows 10.
- open Structorizer
- create a diagram
- save to the desktop
- Structorizer can see the file, it is also present on the Desktop!
- closing Structorizer
- the file is still there
- opening Structorizer again
- the file is still there

Java 1.8.0_121

**Comment by codemanyak** [comment] 2017-02-02 13:48
@fesch Hi Bob, thank you for testing under Windows 10! This just leaves me even more puzzled. What the heck is going on at scorneil's site? Either the Java VM is isolating itself or Windows 10 sandboxes the Java VM. I don't find a different explanation.
@scorneil Do you employ any sandbox software in your Windows 10 installation you may not have been aware of?

**Comment by scorneil** [comment] 2017-02-02 14:37
@codemanyak @fish : I just noticed a green border around my Structorizer program (I don't know if this corresponds with my troubles or not ; I did't really pay attention)  ... Does that ring a bell ?

**Comment by fesch** [comment] 2017-02-02 15:01
very strange ...

BTW, we always learn, so hey ... don't bother ;-)

**Comment by fesch** [comment] 2017-02-02 15:02
green border --> what anti-virus are you running?

**Comment by scorneil** [comment] 2017-02-02 15:05
Windows10 Defender ; nothing  else (that I know of)

**Comment by fesch** [comment] 2017-02-02 15:11
the green border has to do with the sandbox ... but I don't know yet how to disable it ...

**Comment by scorneil** [comment] 2017-02-02 15:13
And where/how would I have unknowingly acquired a sandbox ???

**Comment by codemanyak** [comment] 2017-02-02 18:29
**Comodo** (Comodo Internet security / Comodo Antivirus) is known to frame dubious applications with a green border and may automatically sandbox all unknown applications. You may e.g. have a look here: [Comodo Antivirus 10](http://uk.pcmag.com/comodo-antivirus-8/38825/review/comodo-antivirus-10) or there (though it's related to Windows 7): [Windows 7 forums](https://www.sevenforums.com/general-discussion/280084-strange-frame-around-all-windows.html).

**Sandboxie** is a very popular semi-free Sandbox tool and can also be configured to start certain programs by default in a sandbox and may show a coloured border if enabled to. The border colour is configurable. Look here for instance: [Sandboxie Border Color](https://www.sandboxie.com/index.php?BorderColor).

There are further tools on the market with similar behaviour, e.g. avast! etc.

Of course we cannot know what has been installed on your computers.

This doesn't actually seem to be a Structorizer problem - unless Structorizer induces suspicion by its behaviour or some code patterns (maybe by connecting to URLs if you request the huser guide from menu or enable the version retrieval?).

**Comment by codemanyak** [comment] 2017-02-02 21:31
Since Windows 8, Microsoft brings its own powerfull sandboxing environment, called AppContainer. It is even advised not to let third-party tools like Sandboxie interfere with it because this may lessen the isolation. But whereas I could read some stuff about how to develop apps using it, there is very little documentation around how it might be used (or not) for existing (not to say legacy) desktop applications.

**Comment by scorneil** [comment] 2017-02-03 07:11
@codemanyak : My god ! You are absolutely right ! 
It's actually coming from my browser (Comodo IceDragon) ! It must at some point have installed/activated (??) Comodo Cloud Antivirus !

And it's not just Structorizer that has been sandboxed : jre1.8.0_122/lib/deploy.jar is in there, as well as a bunch of Adobe Creative Cloud stuff ...

![comodo](https://cloud.githubusercontent.com/assets/25483575/22582430/360c1562-e9e7-11e6-97fa-0ce12c0a44c6.png)

Thank you so very much ! Everything is working again as it is supposed to !

**Comment by codemanyak** [comment] 2017-02-03 08:14
I'm glad we could help. And as Bob already told, we learned a lot, too ;-)

**Closed by codemanyak** 2017-02-03 08:14 UTC
