### ISSUE TITLE
Jump statement should support break and continue for loops

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#64] opened 2015-12-16 13:39 UTC
Jump statement only support: exit <return code>
But all loops lack of **break**, **continue** statement in *Executer*,
functional export code should also be generated.

The **for** loop is never breakable. Modifying loop control variable n:=end+1 didn't break.

@codemanyak calling subroutines (with or without paramenters) loaded in the Arranger work's very well.
@codemanyak multiselection with copy, delete work, but move (dragging) didn't.

**Comment by codemanyak** [comment] 2015-12-16 15:11
To leave a loop (of any kind) irregularly you have the following opportunities:
1. Use an empty Jump element - it will do a one-level break.
2. To leave a nested bunch of loops use the keyword "leave" with a cardinal number specifying the number of levels to get out of.

To leave a FOR loop by manipulating the counter value is regarded as extremely bad style and is therefore not supported - by design.
The keywords accepted in Jump elements are still hard-coded (it is prepared to make them configurable, though):
a) **leave** to exit from a loop (number of levels may be added);
b) **return** to exit from a subroutine (result value may be added);
c) **exit** to terminate the entire program irregularly (exit code may be added).

The dragging of a multiselection turned out to be too hazardous and was therefore disabled. By design only single elements may be dragged (and not even this is always stable).

**Comment by codemanyak** [comment] 2015-12-16 15:18
Addendum:
1. By design, the implemetation of a continue instruction was discarded. First, it is not an exit. Second, it doesn't make sense to use it without an alternative. So you may simply revert the alternative and will thus achieve the same effect in a structured way.
2. See issue #23 for a rough specification of the Jump functionality.

**Comment by codemanyak** [comment] 2015-12-18 08:34
@elemhsb May I close this issue?

**Comment by elemhsb** [comment] 2015-12-18 09:59
Thanks for the explanation to exit block, i did't consult the documentation at this point. I have tested the options and they work like expected. This issue can be closed.

**Comment by elemhsb** [comment] 2016-01-15 16:40
Exporting ***exit*** in JUMP block into C/C++, with or without code forget to place a ***;*** behind ).

**Comment by codemanyak** [comment] 2016-01-15 17:25
Thank you, will fix it.

**Closed** 2016-01-17 05:30 UTC
Labels: duplicate
